// <auto-generated />
namespace esfu1_controlEscolar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class timeAviso : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timeAviso));
        
        string IMigrationMetadata.Id
        {
            get { return "201906200347487_timeAviso"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
